language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

#See http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false

env:
  global:
   # Needed for osx builds
   - PKG_CONFIG_PATH: /usr/local/opt/sqlite/lib/pkgconfig
   # Coverity settings
   - secure: "YlP17vf3nSIAR+FGx541X+nNQEY7hNQoEU83S+4PvmJvJacyKJn3uvsB8/WUZIWsTE23mSSquys7yECRnrccgzXJX41EXqRNKgPRWLnerq/djKFYXznY0sJMboRi+qkwD56i2IluhqHQdovdwQBQMWARmxx1a+nz+ujOwFyd3dh2vml1iVG5kZWfN3wpPe5QxgdC6+9Pwbid3RQOxWWclJZTqWYICUGclkLMpQeJcWFFiKnpVSWwad2TE1BEXSl3DzVzzfkfaZaGr0iNTd9Jlo5+MtMRVwtCP4Y3PjS3g+MXZ1dXRy3gfR/OAL5+1HCkOgzqm1Pwp2EFTCQyoYa/2rp4lfikf/EGsI8u02pom7Rqmqhlad8os4rean7Xfj6g47x9Nqc0aNhU7Db16FaSxl4Z6e4sklghtVITZ/y+7WQkY72o1VPlpJv6p8zxpbU1/tmixNLoTjjMBKbxgTYkN0M7SstrStttbkHt0XcQmHTOYWRBRrY2UcO3DQXlgQnFfH3kavtlAowEm6l/TX/m02m3eulDNBOjhGkqL7rd/gUywhwlVsb8iHa4mgFGalKy2PullkvPcV2eOzGg8Z7vRbnkdPDral5xriRkyli21UJM00vA9nFYYJLjWBvFor3BUWZvoyKZz4jCJA9z/ivrRIP+IusIdxeyojNJ/j+vLks="

addons:
  apt:
    packages:
      - build-essential
      - autoconf-archive
      - libssl-dev
      - flex
      - bison
      - astyle
      - libsqlite3-dev
      - tcl
      - tcllib
      - tcl-tls
      - lcov

install:
  - |
    case $TRAVIS_OS_NAME in
    osx)
      brew install autoconf-archive
      brew install sqlite
      brew install lcov
      ;;
    esac
    gem install coveralls-lcov

before_script:
  - |
    if [[ ${TRAVIS_JOB_NUMBER##*.} == 1 ]]; then
      if [[ ${TRAVIS_BRANCH} == master || ${TRAVIS_PULL_REQUEST} != false ]]; then
        # Run coverage only on the first job (gcc+linux) for master and pr's
        COVERAGE=--enable-coverage
      fi
      if [[ ${TRAVIS_BRANCH} == coverity_scan ]]; then
        # Check we're allowed to build
        COVERITY=$(scripts/coverity.sh --build-command)
      fi
      if [[ ${COVERITY} ]]; then
        # We are, install coverity
        scripts/coverity.sh --download
      fi
    fi


script:
  - ./autogen.sh
  - ./configure --enable-debug $COVERAGE
  - $COVERITY make -j2
  - make install
  - testsuite/startall.sh
  - testsuite/wait-links.sh
  - sleep 2
  - make check -j8
  - testsuite/killall.sh

after_success:
  - |
    if [[ "${COVERAGE}" ]]; then
      lcov --compat-libtool --directory . --capture --output-file coverage.info
      lcov --remove coverage.info "/usr/*" --output-file coveralls.info
      coveralls-lcov coveralls.info
    fi
    if [[ ${COVERITY} ]]; then
      scripts/coverity.sh --upload
    fi

after_script:
  - |
    echo Test Suite log:
    cat tests/test-suite.log
  - |
    echo Hub logs:
    cd ~/ircd
    tail -n +1 \
      logs/ircd.log.1 \
      logs/userlog.1 \
      logs/fuserlog.1 \
      logs/operlog.1 \
      logs/foperlog.1 \
      logs/serverlog.1 \
      logs/klinelog.1 \
      logs/killlog.1 \
      logs/operspylog.1 \
      logs/ioerror.1 \
  - |
    echo Leaf1 logs:
    cd ~/ircd
    tail -n +1 \
      logs/ircd.log.2 \
      logs/userlog.2 \
      logs/fuserlog.2 \
      logs/operlog.2 \
      logs/foperlog.2 \
      logs/serverlog.2 \
      logs/klinelog.2 \
      logs/killlog.2 \
      logs/operspylog.2 \
      logs/ioerror.2 \
  - |
    echo Leaf2 logs:
    cd ~/ircd
    tail -n +1 \
      logs/ircd.log.3 \
      logs/userlog.3 \
      logs/fuserlog.3 \
      logs/operlog.3 \
      logs/foperlog.3 \
      logs/serverlog.3 \
      logs/klinelog.3 \
      logs/killlog.3 \
      logs/operspylog.3 \
      logs/ioerror.3 \
