
install:
    - set "OLDPATH=%PATH%"
    - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows"
    - set MSYSTEM=MINGW64
    - pacman --noconfirm -Sy
    - pacman --noconfirm --needed -S pacman-mirrors
    - pacman --noconfirm --needed -S base-devel git zip mingw-w64-x86_64-tcl mingw-w64-x86_64-tcllib mingw-w64-x86_64-openssl mingw-w64-x86_64-toolchain mingw-w64-x86_64-sqlite3
    - ps: >-
        bash -c @"
          # Install autoconf-archive
          exec 0</dev/null 2>&1
          wget --quiet http://gnu.uberglobalmirror.com/autoconf-archive/autoconf-archive-2015.02.24.tar.xz
          tar -xf autoconf-archive-2015.02.24.tar.xz
          cd autoconf-archive-2015.02.24 && ./configure --prefix=/usr && make && make install
        "@

build_script:
    - ps: >-
        bash -c @"
          set -e
          # stdin seems to be invalid on appveyor, so set it to null
          exec 0</dev/null 2>&1
          ./autogen.sh
          ./configure --disable-maintainer-mode --host=x86_64-w64-mingw32 --prefix=C:/ircd --enable-debug
          make
          make install
        
          # Libratbox doesn't get installed for some reason, fix
          cp libratbox/src/.libs/libratbox.dll /c/ircd/bin/
        
          #Copy required libraries
          pushd /mingw64/bin/
          cp libeay32.dll libgcc_s_seh-1.dll libsqlite3-0.dll libssp-0.dll libwinpthread-1.dll ssleay32.dll zlib1.dll /c/ircd/bin
          popd
        
          # And zip for appveyor
          pushd /c/ircd
          zip -r "$APPVEYOR_BUILD_FOLDER/elemental-ircd.zip" *
        "@

after_build:
    - set "PATH=%PATH%;%OLDPATH%"
    - appveyor PushArtifact elemental-ircd.zip

test_script:
    - ps: >-
        bash -c @"
          set -e
        
          echo Tests disabled due to windows build being broken
          exit 0
        
          # Elemental doesn't know how to pull nameservers on windows
          # But will check /etc/resolv.conf (C:\etc\resolv.conf)
          mkdir -p /c/etc
          echo nameserver 8.8.8.8 > /c/etc/resolv.conf
        
          scripts/travis_genssl.sh
          testsuite/startall.sh
          make check
        "@

on_failure:
    - cat tests/test-suite.log
